# Generated by Django 2.0.2 on 2019-09-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=255, unique=True, verbose_name='组名称')),
                ('ProjectId', models.IntegerField(verbose_name='项目id')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('LastUpdateTime', models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间')),
                ('User_id', models.IntegerField(verbose_name='创建者id')),
            ],
            options={
                'verbose_name': '用例分组表',
                'verbose_name_plural': '用例分组表',
                'db_table': 'su_case_group',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('version', models.CharField(max_length=50, verbose_name='项目版本')),
                ('type', models.CharField(choices=[('web', 'web'), ('App', 'App')], max_length=50, verbose_name='项目类型')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.IntegerField(verbose_name='创建者id')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'su_project',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'su_user',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='webkeyword.User')),
            ],
            options={
                'verbose_name': '用户token表',
                'verbose_name_plural': '用户token表',
                'db_table': 'su_user_token',
            },
        ),
    ]
