# Generated by Django 2.0.2 on 2019-09-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webkeyword', '0002_auto_20190921_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casegroup',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
