# Generated by Django 2.2.1 on 2019-09-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkeyword', '0004_auto_20190921_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=200, unique=True, verbose_name='用例名称')),
                ('datails', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('case_group', models.IntegerField(verbose_name='用例组id')),
                ('browser_type', models.CharField(max_length=1024, verbose_name='驱动类型')),
                ('report', models.CharField(max_length=1024, verbose_name='用例结果')),
            ],
            options={
                'verbose_name': '用例表',
                'verbose_name_plural': '用例表',
                'db_table': 'bt_case',
            },
        ),
        migrations.CreateModel(
            name='CaseDatails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField(verbose_name='用例id')),
                ('seq', models.IntegerField(verbose_name='步骤顺序')),
                ('datails', models.CharField(max_length=1024, verbose_name='操作步骤描述')),
                ('Key_word', models.CharField(max_length=1024, verbose_name='关键字')),
                ('type', models.CharField(max_length=1024, verbose_name='定位方式')),
                ('ele', models.CharField(max_length=1024, verbose_name='操作元素')),
                ('value', models.CharField(max_length=1024, verbose_name='操作值')),
                ('run_time', models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '用例表',
                'verbose_name_plural': '用例表',
                'db_table': 'bt_case_datails',
            },
        ),
        migrations.CreateModel(
            name='CheckCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField(verbose_name='用例id')),
                ('seq', models.IntegerField(verbose_name='步骤顺序')),
                ('datails', models.CharField(max_length=1024, verbose_name='操作步骤描述')),
                ('Key_word', models.CharField(max_length=1024, verbose_name='关键字')),
                ('type', models.CharField(max_length=1024, verbose_name='定位方式')),
                ('ele', models.CharField(max_length=1024, verbose_name='操作元素')),
                ('value', models.CharField(max_length=1024, verbose_name='操作值')),
                ('run_time', models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行时间')),
                ('check_type', models.CharField(max_length=1024, verbose_name='断言类型')),
                ('check_value', models.CharField(max_length=1024, verbose_name='断言值')),
            ],
            options={
                'verbose_name': '用例表',
                'verbose_name_plural': '用例表',
                'db_table': 'bt_check_case',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_word_name', models.CharField(max_length=1024, verbose_name='关键字名称')),
                ('key_word_func', models.CharField(max_length=1024, verbose_name='关键字方法')),
            ],
            options={
                'verbose_name': '关键字表',
                'verbose_name_plural': '关键字表',
                'db_table': 'bt_key_word',
            },
        ),
        migrations.AlterField(
            model_name='casegroup',
            name='groupName',
            field=models.CharField(max_length=200, unique=True, verbose_name='组名称'),
        ),
        migrations.AlterModelTable(
            name='casegroup',
            table='bt_case_group',
        ),
        migrations.AlterModelTable(
            name='project',
            table='bt_project',
        ),
        migrations.AlterModelTable(
            name='user',
            table='bt_user',
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='bt_user_token',
        ),
    ]
