# Generated by Django 2.2.1 on 2019-11-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webkeyword', '0006_auto_20191127_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_group',
            new_name='caseGroupId',
        ),
    ]
